config/routes.rb
Mcdaren::Application.routes.draw do

  root to: 'pages#home'

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help',    to: 'pages#help',       via: 'get'
  match '/about',   to: 'pages#about',      via: 'get'
  match '/contact', to: 'pages#contact',    via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "McDaren APP"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Alan Chang
  </small>
  <nav>
    <ul>
      <li><%= link_to "About Us", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "sample app", root_path, id: "logo" %>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
<![endif]-->

<!-- For all other devices -->
<!-- Size should be 32 x 32 pixels -->
<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

app/views/layouts/_sidebar.html.erb
<div class="well sidebar-nav">
  <h3>Sidebar</h3>
  <ul class="nav nav-list">
    <li class="nav-header">Sidebar</li>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Help", help_path %></li>
    <li><%= link_to "About Us", about_path %></li>
    <li><%= link_to "Contact", contact_path %></li>
  </ul>
</div><!--/.well -->

app/views/layouts/member/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'layouts/sidebar' %>
    </div><!--/span-->
    <div class="col-md-9">
      <%= yield %>
    </div>
  </div><!--/row-->
  <%= render 'layouts/footer' %>
</div> <!-- /container -->
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/layouts/mpma/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mcdaren</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/sysadmin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mcdaren</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>